import { Calendar, CheckCircle, AlertTriangle, TrendingUp, Presentation, Video, Image as ImageIcon } from 'lucide-react';

export default function BriefingTerminal() {
  return (
    <div className="p-4 md:p-6 flex flex-col items-center min-w-0">
      <div className="max-w-4xl w-full bg-bg-card border border-border-subtle rounded-3xl shadow-2xl overflow-hidden mt-2 md:mt-4">
        
        <div className="border-b-4 border-[#f64e6e] p-6 md:p-8 bg-gradient-to-b from-[#1a080c] to-bg-card">
          <div className="flex flex-col md:flex-row justify-between items-start mb-6 gap-4">
            <div>
              <h1 className="text-2xl md:text-3xl font-black uppercase tracking-tighter text-white mb-2">Morningstar Intelligence</h1>
              <div className="flex items-center gap-4 text-[#f64e6e] font-mono text-xs md:text-sm font-bold">
                <span className="flex items-center gap-2"><Calendar className="w-4 h-4"/> 2026-04-02</span>
                <span className="bg-[#f64e6e]/10 px-2 py-0.5 rounded-sm">STATUS: OPERATIONAL</span>
              </div>
            </div>
            <div className="text-left md:text-right border-l md:border-l-0 border-border-subtle pl-4 md:pl-0">
              <div className="text-text-tertiary uppercase text-xs tracking-widest font-bold mb-1">Generated By</div>
              <div className="text-white font-black text-sm md:text-lg tracking-tighter max-w-[150px] md:max-w-none">MORNINGSTAR AGENT</div>
            </div>
          </div>
          
          <p className="text-text-secondary text-sm md:text-base leading-relaxed max-w-3xl">
            Good morning, Director. All primary subsystems are nominal. We executed 24 automated tasks overnight with a 96% success rate. The Content Factory has queued 3 assets for your review.
          </p>
        </div>

        <div className="p-6 md:p-8 grid grid-cols-1 lg:grid-cols-2 gap-8">
          
          {/* Ops & Intel */}
          <div className="space-y-8">
            <div>
              <h3 className="text-white uppercase font-black tracking-tighter mb-4 border-b border-border-subtle pb-3 flex items-center gap-2">
                <CheckCircle className="w-5 h-5 text-emerald-400"/> Ops Summary
              </h3>
              <ul className="space-y-4">
                <li className="flex justify-between items-center bg-bg-deep p-3 rounded-xl border border-border-subtle">
                  <span className="text-text-secondary text-sm font-bold">Missions Completed</span>
                  <span className="font-mono text-emerald-400 font-bold bg-emerald-400/10 px-3 py-1 rounded-md">24 / 25</span>
                </li>
                <li className="flex justify-between items-center bg-bg-deep p-3 rounded-xl border border-border-subtle">
                  <span className="text-text-secondary text-sm font-bold">Failed Missions</span>
                  <span className="font-mono text-rose-500 font-bold bg-rose-500/10 px-3 py-1 rounded-md">1</span>
                </li>
                <li className="flex justify-between items-center bg-bg-deep p-3 rounded-xl border border-border-subtle">
                  <span className="text-text-secondary text-sm font-bold">Viral Hits Predicted</span>
                  <span className="font-mono text-amber-500 font-bold bg-amber-500/10 px-3 py-1 rounded-md">2</span>
                </li>
              </ul>
            </div>

            <div>
              <h3 className="text-white uppercase font-black tracking-tighter mb-4 border-b border-border-subtle pb-3 flex items-center gap-2">
                <AlertTriangle className="w-5 h-5 text-amber-500"/> Notice
              </h3>
              <div className="bg-amber-500/10 border border-amber-500/20 rounded-xl p-4 text-sm text-amber-500/90 leading-relaxed">
                Gateway Latency spiked at 03:00 to 140ms. Redis queue depth hit warning threshold but recovered gracefully. 
              </div>
            </div>
            
            <div>
              <h3 className="text-white uppercase font-black tracking-tighter mb-4 border-b border-border-subtle pb-3 flex items-center gap-2">
                <TrendingUp className="w-5 h-5 text-indigo-400"/> Top Trend Detected
              </h3>
              <div className="bg-bg-deep p-5 border border-border-subtle rounded-xl">
                <div className="text-xl font-black text-white mb-2">#AI_Agents_2026</div>
                <div className="text-sm text-text-secondary mb-5 leading-relaxed">Viability Score: <span className="text-emerald-400 font-bold">88</span>, Momentum: <span className="text-brand-start font-bold">High</span>. Recommended action: Deploy The Hook for a thread breakdown.</div>
                <button className="rounded-full w-full bg-indigo-500 hover:bg-indigo-400 text-white py-3 text-xs uppercase font-black tracking-wider transition-colors shadow-[0_0_15px_-3px_rgba(99,102,241,0.5)]">
                  Dispatch Action
                </button>
              </div>
            </div>
          </div>

          {/* Generated Pipeline Elements */}
          <div className="space-y-8">
            <div>
              <h3 className="text-white uppercase font-black tracking-tighter mb-4 border-b border-border-subtle pb-3 flex items-center gap-2">
                <Presentation className="w-5 h-5 text-[#f64e6e]"/> Generated Carousel
              </h3>
              <div className="bg-bg-deep p-1 rounded-2xl border border-border-subtle flex overflow-x-auto snap-x space-x-2 pb-2">
                {['1. Hook', '2. Context', '3. Problem', '4. Evidence', '5. CTA'].map((slide) => (
                  <div key={slide} className="snap-start flex-shrink-0 w-32 h-40 bg-bg-card border border-border-subtle rounded-xl p-3 flex flex-col justify-between group cursor-pointer hover:border-[#f64e6e] transition-colors relative overflow-hidden">
                    <div className="text-[10px] uppercase font-bold text-text-tertiary">{slide.split('.')[0]} / 5</div>
                    <div className="text-xs font-bold text-white leading-tight">{slide.split('. ')[1]}</div>
                    <div className="w-full h-1 bg-border-subtle rounded-full mt-2 overflow-hidden">
                      <div className="h-full bg-[#f64e6e] w-0 group-hover:w-full transition-all duration-500"></div>
                    </div>
                  </div>
                ))}
              </div>
            </div>

            <div>
              <h3 className="text-white uppercase font-black tracking-tighter mb-4 border-b border-border-subtle pb-3 flex items-center gap-2">
                <Video className="w-5 h-5 text-sky-400"/> Short-Video Script
              </h3>
              <div className="bg-bg-deep rounded-xl border border-border-subtle overflow-hidden text-sm">
                <div className="flex border-b border-border-subtle">
                  <div className="w-16 bg-bg-card p-3 font-mono text-xs text-sky-400 border-r border-border-subtle">0-3s</div>
                  <div className="p-3 text-white font-medium">Hook: Visual pattern interrupt.</div>
                </div>
                <div className="flex border-b border-border-subtle">
                  <div className="w-16 bg-bg-card p-3 font-mono text-xs text-sky-400 border-r border-border-subtle">3-15s</div>
                  <div className="p-3 text-text-secondary">Setup: Introduce the pain point.</div>
                </div>
                <div className="flex border-b border-border-subtle">
                  <div className="w-16 bg-bg-card p-3 font-mono text-xs text-sky-400 border-r border-border-subtle">15-75s</div>
                  <div className="p-3 text-text-secondary">Body: Fast cuts, data points.</div>
                </div>
                <div className="flex">
                  <div className="w-16 bg-bg-card p-3 font-mono text-xs text-sky-400 border-r border-border-subtle">75-90s</div>
                  <div className="p-3 text-brand-end font-bold">CTA: Follow for more alpha.</div>
                </div>
              </div>
            </div>

            <div>
              <h3 className="text-white uppercase font-black tracking-tighter mb-4 border-b border-border-subtle pb-3 flex items-center gap-2">
                <ImageIcon className="w-5 h-5 text-emerald-400"/> B-Roll Assets
              </h3>
              <div className="grid grid-cols-2 gap-3">
                <div className="bg-bg-deep border border-border-subtle p-3 rounded-xl flex flex-col items-center justify-center gap-2 cursor-pointer hover:border-emerald-400 transition-colors h-24">
                  <span className="text-xs font-bold text-text-secondary uppercase">API: Pexels</span>
                  <span className="text-[10px] text-emerald-400 bg-emerald-400/10 px-2 py-1 rounded">3 Assets Match</span>
                </div>
                <div className="bg-bg-deep border border-border-subtle p-3 rounded-xl flex flex-col items-center justify-center gap-2 cursor-pointer hover:border-emerald-400 transition-colors h-24">
                  <span className="text-xs font-bold text-text-secondary uppercase">API: Pixabay</span>
                  <span className="text-[10px] text-emerald-400 bg-emerald-400/10 px-2 py-1 rounded">1 Asset Match</span>
                </div>
              </div>
            </div>

          </div>

        </div>
      </div>
    </div>
  );
}
